# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Larissa Triess | Personal Webpage
author: Larissa Triess
description: Personal Webpage of Larissa Triess, PhD student
icon: assets/img/favicon.ico # path to page icon
teaser: # path to page preview image

# Settings for navigation bar
avatar: assets/img/avatar.jpg # path to profile avatar image

# Settings for landing page
landing_first: Larissa
landing_last: Triess
subheading: PhD Student · Deep Generative Models · Autonomous Driving · Stuttgart, Germany
intro: >-
  I am a passionate student and researcher in the field of machine learning and autonomous driving.
  The ever changing world and unpredictable future drives me to keep learning constantly.

# Social settings
email: <!-- spam-stop -->mail@triess.eu
linkedin_url: https://www.linkedin.com/in/triess-larissa
github_url: https://github.com/ltriess
googlescholar_url: https://scholar.google.de/citations?user=cBH8pFUAAAAJ&hl=de
arxiv_url: http://arxiv.org/a/triess_l_1

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: https://larissa.triess.eu # the base hostname & protocol for your site

# Google Analytics Tracking ID
google_analytics: UA-155335821-1

# Required for the page to work
collections: [sections]
